use rdev::Key;
use std::collections::HashMap;

pub fn all() -> HashMap<&'static str, Key> {
    HashMap::from([ 
        ("a", Key::KeyA),
        ("b", Key::KeyB),
        ("c", Key::KeyC),
        ("d", Key::KeyD),
        ("e", Key::KeyE),
        ("f", Key::KeyF),
        ("g", Key::KeyG),
        ("h", Key::KeyH),
        ("i", Key::KeyI),
        ("j", Key::KeyJ),
        ("k", Key::KeyK),
        ("l", Key::KeyL),
        ("m", Key::KeyM),
        ("n", Key::KeyN),
        ("o", Key::KeyO),
        ("p", Key::KeyP),
        ("q", Key::KeyQ),
        ("r", Key::KeyR),
        ("s", Key::KeyS),
        ("t", Key::KeyT),
        ("u", Key::KeyU),
        ("v", Key::KeyV),
        ("w", Key::KeyW),
        ("x", Key::KeyX),
        ("y", Key::KeyY),
        ("z", Key::KeyZ),

        ("0", Key::Num0),
        ("1", Key::Num1),
        ("2", Key::Num2),
        ("3", Key::Num3),
        ("4", Key::Num4),
        ("5", Key::Num5),
        ("6", Key::Num6),
        ("7", Key::Num7),
        ("8", Key::Num8),
        ("9", Key::Num9),

        ("f1", Key::F1),
        ("f2", Key::F2),
        ("f3", Key::F3),
        ("f4", Key::F4),
        ("f5", Key::F5),
        ("f6", Key::F6),
        ("f7", Key::F7),
        ("f8", Key::F8),
        ("f9", Key::F9),
        ("f10", Key::F10),
        ("f11", Key::F11),
        ("f12", Key::F12),

        ("left", Key::LeftArrow),
        ("right", Key::RightArrow),
        ("up", Key::UpArrow),
        ("down", Key::DownArrow),

        ("home", Key::Home),
        ("end", Key::End),
        ("pageup", Key::PageUp),
        ("pagedown", Key::PageDown),

        ("backspace", Key::Backspace),
        ("delete", Key::Delete),
        ("enter", Key::Return),
        ("return", Key::Return),
        ("tab", Key::Tab),
        ("space", Key::Space),
        ("escape", Key::Escape),
        ("esc", Key::Escape),

        ("shiftleft", Key::ShiftLeft),
        ("shiftright", Key::ShiftRight),

        ("controlleft", Key::ControlLeft),
        ("controlright", Key::ControlRight),

        ("alt", Key::Alt),

        ("metaleft", Key::MetaLeft),
        ("metaright", Key::MetaRight),

        ("-", Key::Minus),
        ("=", Key::Equal),
        ("[", Key::LeftBracket),
        ("]", Key::RightBracket),
        ("\\", Key::BackSlash),
        (";", Key::SemiColon),
        ("'", Key::Quote),
        (",", Key::Comma),
        (".", Key::Dot),
        ("/", Key::Slash),
        ("`", Key::BackQuote),
    ])
}